/* ========================================
   GitPulse — Export
   html2canvas screenshot, copy/download
   ======================================== */

const ExportCard = (() => {
  let currentStats = null;

  function setStats(stats) {
    currentStats = stats;
  }

  function open() {
    if (!currentStats) return;
    renderExportCard(currentStats);
    document.getElementById('export-modal').hidden = false;
  }

  function close() {
    document.getElementById('export-modal').hidden = true;
  }

  function renderExportCard(stats) {
    const card = document.getElementById('export-card');
    const scoreColor = Stats.getScoreColor(stats.score);
    const topLangs = stats.languages.slice(0, 3);
    const maxPct = topLangs.length > 0 ? Math.max(...topLangs.map(l => parseFloat(l.percentage))) : 1;

    // Mini heatmap data
    const heatDays = Object.entries(stats.heatmapData).sort((a, b) => a[0].localeCompare(b[0]));
    const heatWeeks = [];
    let week = [];
    const startDay = new Date(heatDays[0]?.[0] || new Date()).getDay();
    for (let i = 0; i < startDay; i++) week.push(0);
    heatDays.forEach(([, count]) => {
      if (week.length === 7) { heatWeeks.push(week); week = []; }
      week.push(count);
    });
    while (week.length < 7) week.push(0);
    heatWeeks.push(week);

    const heatColors = ['#161b22', '#0e4429', '#006d32', '#26a641', '#39d353'];
    function heatColor(c) {
      if (c === 0) return heatColors[0];
      if (c <= 2) return heatColors[1];
      if (c <= 4) return heatColors[2];
      if (c <= 7) return heatColors[3];
      return heatColors[4];
    }

    card.innerHTML = `
      <div class="export-top">
        <img class="export-avatar" src="${stats.user.avatar_url}" alt="" crossorigin="anonymous">
        <div class="export-user-info">
          <div class="export-username">${stats.user.login}</div>
          <div class="export-bio">${stats.user.bio || stats.user.name || ''}</div>
        </div>
        <div class="export-score-badge">
          <div class="export-score-value" style="color:${scoreColor}">${stats.score}</div>
          <div class="export-score-label">Score</div>
        </div>
      </div>

      <div class="export-stats">
        <div class="export-stat">
          <div class="export-stat-value">${formatExNum(stats.user.public_repos)}</div>
          <div class="export-stat-label">Repos</div>
        </div>
        <div class="export-stat">
          <div class="export-stat-value">${formatExNum(stats.totalStars)}</div>
          <div class="export-stat-label">Stars</div>
        </div>
        <div class="export-stat">
          <div class="export-stat-value">${formatExNum(stats.totalForks)}</div>
          <div class="export-stat-label">Forks</div>
        </div>
        <div class="export-stat">
          <div class="export-stat-value">${formatExNum(stats.user.followers)}</div>
          <div class="export-stat-label">Followers</div>
        </div>
      </div>

      <div class="export-langs">
        ${topLangs.map(l => `
          <div class="export-lang-row">
            <span class="export-lang-name">${l.name}</span>
            <div class="export-lang-bar-track">
              <div class="export-lang-bar-fill" style="width:${(parseFloat(l.percentage) / maxPct) * 100}%;background:${l.color}"></div>
            </div>
            <span class="export-lang-pct">${l.percentage}%</span>
          </div>
        `).join('')}
      </div>

      <div class="export-heatmap">
        ${heatWeeks.map(w => `
          <div class="export-heatmap-week">
            ${w.map(c => `<div class="export-heatmap-cell" style="background:${heatColor(c)}"></div>`).join('')}
          </div>
        `).join('')}
      </div>

      <div class="export-watermark">
        <div class="export-watermark-left">
          <svg viewBox="0 0 40 24" fill="none"><path d="M2 12h4l3-8 4 16 3-12 2 4h8" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"/></svg>
          Generated by GitPulse
        </div>
        <div class="export-watermark-right">github.com/${stats.user.login}</div>
      </div>
    `;
  }

  async function downloadPNG() {
    const card = document.getElementById('export-card');
    try {
      const canvas = await html2canvas(card, {
        backgroundColor: '#0a0a0f',
        scale: 2,
        useCORS: true,
        allowTaint: true,
        width: 600,
        height: 315
      });

      const link = document.createElement('a');
      link.download = `gitpulse-${currentStats.user.login}.png`;
      link.href = canvas.toDataURL('image/png');
      link.click();
      Toast.show('PNG downloaded!', 'success');
    } catch {
      Toast.show('Failed to generate image. Try again.', 'error');
    }
  }

  async function copyToClipboard() {
    const card = document.getElementById('export-card');
    try {
      const canvas = await html2canvas(card, {
        backgroundColor: '#0a0a0f',
        scale: 2,
        useCORS: true,
        allowTaint: true,
        width: 600,
        height: 315
      });

      canvas.toBlob(async (blob) => {
        try {
          await navigator.clipboard.write([
            new ClipboardItem({ 'image/png': blob })
          ]);
          Toast.show('Copied to clipboard!', 'success');
        } catch {
          Toast.show('Clipboard access denied. Try downloading instead.', 'warning');
        }
      }, 'image/png');
    } catch {
      Toast.show('Failed to generate image.', 'error');
    }
  }

  function formatExNum(n) {
    if (n >= 1000000) return (n / 1000000).toFixed(1) + 'M';
    if (n >= 1000) return (n / 1000).toFixed(1) + 'k';
    return n.toString();
  }

  return { setStats, open, close, downloadPNG, copyToClipboard };
})();
